### PR TITLE
Add API request results

### PR DESCRIPTION
**Pull request by MargitStar**

### CODE REVIEW

**Comment by MargitStar** [comment]
@lexastef please review

**Comment by lexastef** [comment]
@MargitStar sorry forget to leave a comment here.
Reviewed and approved for an 8 (no post collections and TitterAPI)

**Comment by lexastef** [comment]
'+ I saw updates regarding third lab in master
Mark updated to 7. Thanks!

**Comment by MargitStar** [comment]
Ok, thanks.

**Comment by lexastef** [comment]
You are welcome ;)
Keep going @MargitStar 👍 
A fine of time is increases. It's really helps if the major labs will be at least initially reviewed to have a minimum "-" for a time.

**Pull request closed without merging**
